<?php

namespace AppBundle\Repository;

/**
 * MarketyInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketyInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
