<?php

namespace markety\OfferBundle\Repository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class OfferRepository extends \Doctrine\ORM\EntityRepository
{
}
