markety_offer_add:
    path:   /new_service_offer
    defaults:  { _controller: marketyOfferBundle:Management:add }

markety_offer_persist:
    path:   /new_service_offer_add
    defaults:  { _controller: marketyOfferBundle:Management:persist }